### ISSUE TITLE
Templates for v8.0

### ISSUE THREAD

**Issue by mohamedmagdy** [JulienDrecq/PycharmTemplateOdoo#3]
Hi
I found your repo for version 7.0 after I started my repo for v8.0:
https://github.com/mohamedmagdy/odoo-pycharm-templates
I think we can work together :dancers:

**Comment by gorjuce** [comment]
any decision about ?
It would web great ...

**Comment by JulienDrecq** [comment]
Hi, I begin to add templates for Odoo v8.
Just a little patience, it happens :)

Thanks guys

**Comment by eMh4x** [comment]
Hello Guys,

Actually we don't have many Odoo with the new API (v8/v9/v10).
And there is already some templates for the new API (basic CRUD functions) and that is just enough for us.
We'll gonna add some v8 features (xml, python) when we'll really need it.

Have a nice day.
